
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FPDemo(object):
    def setupUi(self, FPDemo):
        FPDemo.setObjectName("FPDemo")
        FPDemo.resize(1059, 814)
        self.centralwidget = QtWidgets.QWidget(FPDemo)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(11, 11, 233, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Transaction_1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.Transaction_1.setObjectName("Transaction_1")
        self.gridLayout.addWidget(self.Transaction_1, 0, 1, 1, 1)
        self.Transaction_4 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.Transaction_4.setObjectName("Transaction_4")
        self.gridLayout.addWidget(self.Transaction_4, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.Transaction_3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.Transaction_3.setObjectName("Transaction_3")
        self.gridLayout.addWidget(self.Transaction_3, 3, 1, 1, 1)
        self.Transaction_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.Transaction_2.setObjectName("Transaction_2")
        self.gridLayout.addWidget(self.Transaction_2, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.FPButton = QtWidgets.QPushButton(self.centralwidget)
        self.FPButton.setGeometry(QtCore.QRect(11, 129, 93, 28))
        self.FPButton.setObjectName("FPButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(450, 20, 57, 87))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.layoutWidget.raise_()
        self.gridLayoutWidget.raise_()
        self.FPButton.raise_()
        FPDemo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FPDemo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1059, 26))
        self.menubar.setObjectName("menubar")
        FPDemo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FPDemo)
        self.statusbar.setObjectName("statusbar")
        FPDemo.setStatusBar(self.statusbar)

        self.retranslateUi(FPDemo)
        QtCore.QMetaObject.connectSlotsByName(FPDemo)

    def retranslateUi(self, FPDemo):
        _translate = QtCore.QCoreApplication.translate
        FPDemo.setWindowTitle(_translate("FPDemo", "FPDemo"))
        self.Transaction_1.setText(_translate("FPDemo", "a,b,c,d"))
        self.Transaction_4.setText(_translate("FPDemo", "c,d"))
        self.label_3.setText(_translate("FPDemo", "Transaction 3 :"))
        self.label_2.setText(_translate("FPDemo", "Transaction 1 :"))
        self.label.setText(_translate("FPDemo", "Transaction 2 :"))
        self.Transaction_3.setText(_translate("FPDemo", "a,d"))
        self.Transaction_2.setText(_translate("FPDemo", "a,b,c"))
        self.label_4.setText(_translate("FPDemo", "Transaction 4 :"))
        self.FPButton.setText(_translate("FPDemo", "Run FP"))
        self.label_8.setText(_translate("FPDemo", "TextLabel"))
        self.label_5.setText(_translate("FPDemo", "TextLabel"))
        self.label_7.setText(_translate("FPDemo", "TextLabel"))
        self.label_6.setText(_translate("FPDemo", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FPDemo = QtWidgets.QMainWindow()
    ui = Ui_FPDemo()
    ui.setupUi(FPDemo)
    FPDemo.show()
    sys.exit(app.exec_())
